### ISSUE TITLE
Reducing Duplicate CSS

### ISSUE THREAD

**Issue by jim-rosales** [lcampb77/prj-rev-bwfs-dasmoto#4]
After analyzing your stylesheet, I noticed that in some areas you had CSS styles that are needed or duplicate styles. When writing CSS if you ever find yourself writing the same styles for multiple sections, it is best to rewrite your stylesheet and apply the styles they all share at the same time. 

The reason for this is because it makes it easier to make changes in the future to your page and helps increase the readability of your stylesheet. 

For example, I noticed your applied the `Helvetica` font-family here which was perfect
```CSS
h1, h2, h3, p {
  font-family: Helvetica;
}
```

But then you applied the font-family again in this rule:
```CSS
h1 {
 /** Not needed since the rule above already applied the font
  font-family: Helvetica; **/
  font-size: 100px;
  font-weight: bold;
  color: khaki;
  text-align: center;
}
```

Then for your h2's a better alternative to applying the desired styles is to do the following:
```CSS
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brushes h2 {
  background-color: mediumspringgreen;
}

.frames h2 {
  background-color: lightcoral;
}

.paint h2 {
  background-color: skyblue;
}
```

This way you only apply the different background-color to each h2, and they inherit all the styles they share. In this case, they would also inherit the font-family from the first CSS rule you have on the page since they are all h2s. 

https://github.com/lcampb77/prj-rev-bwfs-dasmoto/blob/29149b4fa1d4229bd426663ff44d233baad6f9b2/dasmoto/resources/index.css#L13-L35
